[build]
  publish = "."

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/schema.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
